// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHuQBD3NJ0t2LZpkUNXLH44xVvAPWeds0',
    appId: '1:627078612621:web:f1b8c4c5ccd5cc4760c4c4',
    messagingSenderId: '627078612621',
    projectId: 'oxdo-firebase1',
    authDomain: 'oxdo-firebase1.firebaseapp.com',
    storageBucket: 'oxdo-firebase1.appspot.com',
    measurementId: 'G-J5K9NKC8HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYHv47eRDQzgiEMeq4Jr6QCNwwnztso14',
    appId: '1:627078612621:android:a1efec7990a29fec60c4c4',
    messagingSenderId: '627078612621',
    projectId: 'oxdo-firebase1',
    storageBucket: 'oxdo-firebase1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZrYyYK03RBfNdF5ni5XRUtt3D97xrodY',
    appId: '1:627078612621:ios:25231c8714819ae560c4c4',
    messagingSenderId: '627078612621',
    projectId: 'oxdo-firebase1',
    storageBucket: 'oxdo-firebase1.appspot.com',
    iosBundleId: 'com.oxdotechnologies.oxdoFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZrYyYK03RBfNdF5ni5XRUtt3D97xrodY',
    appId: '1:627078612621:ios:25231c8714819ae560c4c4',
    messagingSenderId: '627078612621',
    projectId: 'oxdo-firebase1',
    storageBucket: 'oxdo-firebase1.appspot.com',
    iosBundleId: 'com.oxdotechnologies.oxdoFirebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHuQBD3NJ0t2LZpkUNXLH44xVvAPWeds0',
    appId: '1:627078612621:web:465052fe70b08eb060c4c4',
    messagingSenderId: '627078612621',
    projectId: 'oxdo-firebase1',
    authDomain: 'oxdo-firebase1.firebaseapp.com',
    storageBucket: 'oxdo-firebase1.appspot.com',
    measurementId: 'G-PEEB9GFMRG',
  );
}
